# Generated by Django 5.2 on 2025-05-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='auction_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
