# Generated by Django 5.2 on 2025-05-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0002_alter_productmodel_auction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='divident_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
