# Generated by Django 5.2 on 2025-05-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0003_alter_productmodel_divident_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='auction_date',
            new_name='auction_day',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='divident_date',
            new_name='divident_day',
        ),
    ]
