# Generated by Django 5.2 on 2025-05-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0004_rename_auction_date_productmodel_auction_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='chit_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
