# Generated by Django 5.2 on 2025-05-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0005_alter_productmodel_chit_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='agent_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
