# Generated by Django 5.2 on 2025-05-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0006_alter_userprofilemodel_agent_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='auction_day',
            new_name='auction_date',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='divident_day',
            new_name='divident_date',
        ),
    ]
