# Generated by Django 5.2 on 2025-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0007_rename_auction_day_productmodel_auction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='draw_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
