# Generated by Django 5.2 on 2025-05-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inkludechit', '0008_alter_productmodel_draw_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='multi_division_auction_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='multi_division_auction_eligibility',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='multi_division_divident_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
